config/routes.rb
Pinpic::Application.routes.draw do
  
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  
  resources :pins

  root 'pins#index'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  
  # associations
  belongs_to :user
  has_attached_file :image, :styles => { :large => "515x572>", :medium => "200x200>", :small => "150x150>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"


  
  # validations
  validates_presence_of :description, :user_id
  validates_attachment :image, presence: true,
                              content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif' ] },
                              size: { less_than: 3.megabytes } 
end

app/models/user.rb
class User < ActiveRecord::Base

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login

  has_many :pins

  #https://github.com/thoughtbot/paperclip#quick-start
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:recoverable
         :rememberable, :trackable, :validatable

  # https://github.com/plataformatec/devise/wiki/How-To%3a-Allow-users-to-sign-in-using-their-username-or-email-address#tell-devise-to-use-login-in-the-authentication_keys
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["username = :value OR lower(email) = lower(:value)", { :value => login }]).first
    else
      where(conditions).first
    end
  end        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #https://github.com/plataformatec/devise#strong-parameters
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :email, :password, :remember_me) }
  end  


  # declearing methods inorder to user devise resource within Modals 
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  helper_method :resource, :resource_name, :devise_mapping
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
    
  end

  def contact
    
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index]

  def index
    @pins = Pin.order("created_at desc")
  end

  def show
    @pin = Pin.find(params[:id])
  end

  def new
    @pin = current_user.pins.new
  end

  def edit

  end

  def create
    @pin = current_user.pins.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pin }
      else
        format.html { render action: 'new' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, alert: 'Pin was deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = current_user.pins.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :user_id, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

# Rails flash messages using Twitter Bootstrap
# https://gist.github.com/suryart/7418454
def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end
 
  def flash_messages(opts = {})
    capture do
      flash.each do |msg_type, message|
        concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
          concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
          concat message 
        end)
      end
      nil
    end
  end
  # captures the content so it isn’t appended straight to the page. Instead, it’s built up as a separate string, for your custom helper to return
  # http://thepugautomatic.com/2013/06/helpers/
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
     <div class="alert alert-danger fade in">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
       <h4>Oh snap! You got an error!</h4>
       #{messages}
     </div>
    HTML
    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="row">
  <small>
    <a href="#">Pin Pic</a>
    by Ahmed NAdar
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Pin Pic", root_path, class: "navbar-brand" %>
    </div>
    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "About",  about_path %></li>
        <li><%= link_to "Contact",contact_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Add +", new_pin_path %></li>
          <li><%= link_to current_user.username, edit_user_registration_path %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", "", data: {toggle: "modal", target: "#myModal"} %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinpic</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <div class="container">
    <%= render "layouts/header" %>
    <%= render "pages/modals/login" %>
    <%= flash_messages %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </div
</body>
</html>

app/views/pages/_home.html.erb
<% if user_signed_in? %>
  <p>Welcome back <strong><%= current_user.username %></strong>, you are logged in!</p>
<% else %>
  <div class="jumbotron center">
    <h1>Wecome to Pin Pic</h1>
    <p>This the home page for Pin Pic where you can share your pictures online.</p>
    <p><%= button_to "Be part of the family!", "", role: "button", class: "btn btn-info btn-lg", data: {toggle: "modal", target: "#myModal"} %></p>
  </div>
  
<% end %>









 

app/views/pages/about.html.erb
<h1>About Us</h1>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>

app/views/pages/home.html.erb
<% if user_signed_in? %>
  <p>Welcome back <strong><%= current_user.username %></strong>, you are logged in!</p>
  <p>Enjoy you pins <%= current_user.pins %></p>
<% else %>
  <div class="jumbotron center">
    <h1>Wecome to Pin Pic</h1>
    <p>This the home page for Pin Pic where you can share your pictures online.</p>
    <p><%= button_to "Be part of the family!", "", role: "button", class: "btn btn-info btn-lg", data: {toggle: "modal", target: "#myModal"} %></p>
  </div>
  
<% end %>









 

app/views/pages/modals/_login.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Register with Pin Pic</h4>
      </div>
      <div class="modal-body">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#login" data-toggle="tab">Login</a></li>
          <li><a href="#signup" data-toggle="tab">Sign up</a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
          <div class="tab-pane fade in active" id="login">
            <%= form_for(resource, :as => resource_name, :url => session_path(resource_name), html: { class: "form-horizontal top-30-margin" }) do |f| %>
              <div class="form-group">
                <%= f.label :login, class: "col-sm-2 control-label", for: "inputEmail3" %>
                <div class="col-sm-10 input-group">
                  <span class="input-group-addon">
                    <span class="glyphicon glyphicon-user"></span>
                  </span>
                  <%= f.text_field :login, :autofocus => true, class: "form-control", id: "inputEmail3", placeholder:"Login" %>
                </div>
              </div>
              <div class="form-group">
                <%= f.label :password, class: "col-sm-2 control-label", for: "inputPassword3" %>
                <div class="col-sm-10 input-group">
                  <span class="input-group-addon">
                    <span class="glyphicon glyphicon-asterisk"></span>
                  </span>
                  <%= f.password_field :password, class: "form-control", id: "inputPassword3", placeholder:"Password" %>
                </div>
              </div>
              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <div class="checkbox">
                    <% if devise_mapping.rememberable? -%>
                      <%= f.check_box :remember_me %> <%= f.label :remember_me %>
                    <% end -%>                  
                  </div>
                </div>
              </div>
              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <%= f.submit 'Login', class: "btn btn-default" %>
                </div>
              </div>
            <% end %> 
          </div>
          <div class="tab-pane fade" id="signup">
            <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), html: { class: "form-horizontal top-30-margin" }) do |f| %>
              <%= devise_error_messages! %>

              <div class="form-group">
                <%= f.label :username, class: "col-sm-2 control-label", for: "inputEmail3" %>
                <div class="col-sm-10 input-group">
                  <span class="input-group-addon">
                    <span class="glyphicon glyphicon-user"></span>
                  </span>
                  <%= f.text_field :username, :autofocus => true, class: "form-control", id: "inputEmail3", placeholder:"Username" %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :email, class: "col-sm-2 control-label", for: "inputEmail3" %>
                <div class="col-sm-10 input-group">
                  <span class="input-group-addon">
                    <span class="glyphicon glyphicon-envelope"></span>
                  </span>
                  <%= f.email_field :email, class: "form-control", id: "inputEmail3", placeholder:"Email" %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :password, class: "col-sm-2 control-label", for: "inputPassword3" %>
                <div class="col-sm-10 input-group">
                  <span class="input-group-addon">
                    <span class="glyphicon glyphicon-asterisk"></span>
                  </span>
                  <%= f.password_field :password, class: "form-control", id: "inputPassword3", placeholder:"Password" %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :'confirm password', class: "col-sm-2 control-label", for: "inputPassword3" %>
                <div class="col-sm-10 input-group">
                  <span class="input-group-addon">
                    <span class="glyphicon glyphicon-asterisk"></span>
                  </span>
                  <%= f.password_field :password_confirmation, class: "form-control", id: "inputPassword3", placeholder:"Password" %>
                </div>
              </div>

              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <%= f.submit :'Sign up', class: "btn btn-default" %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div> -->
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/pages/modals/_sign.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Register with Pin Pic</h4>
      </div>
      <div class="modal-body">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#signin" data-toggle="tab">Sign in</a></li>
          <li><a href="#signup" data-toggle="tab">Sign up</a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
          <div class="tab-pane fade in active" id="signin">
            <%= form_for(resource, :as => resource_name, :url => session_path(resource_name), html: { class: "form-horizontal top-30-margin" }) do |f| %>
              <div class="form-group">
                <%= f.label :login, class: "col-sm-2 control-label", for: "inputEmail3" %>
                <div class="col-sm-10 input-group">
                  <span class="input-group-addon">
                    <span class="glyphicon glyphicon-user"></span>
                  </span>
                  <%= f.text_field :login, :autofocus => true, class: "form-control", id: "inputEmail3", placeholder:"Email" %>
                </div>
              </div>
              <div class="form-group">
                <%= f.label :password, class: "col-sm-2 control-label", for: "inputPassword3" %>
                <div class="col-sm-10 input-group">
                  <span class="input-group-addon">
                    <span class="glyphicon glyphicon-asterisk"></span>
                  </span>
                  <%= f.password_field :password, class: "form-control", id: "inputPassword3", placeholder:"Password" %>
                </div>
              </div>
              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <div class="checkbox">
                    <% if devise_mapping.rememberable? -%>
                      <%= f.check_box :remember_me %> <%= f.label :remember_me %>
                    <% end -%>                  
                  </div>
                </div>
              </div>
              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <%= f.submit :'Sign in', class: "btn btn-default" %>
                </div>
              </div>
            <% end %> 
          </div>
          <div class="tab-pane fade" id="signup">
            <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), html: { class: "form-horizontal top-30-margin" }) do |f| %>
              <%= devise_error_messages! %>

              <div class="form-group">
                <%= f.label :username, class: "col-sm-2 control-label", for: "inputEmail3" %>
                <div class="col-sm-10 input-group">
                  <span class="input-group-addon">
                    <span class="glyphicon glyphicon-user"></span>
                  </span>
                  <%= f.text_field :username, :autofocus => true, class: "form-control", id: "inputEmail3", placeholder:"Username" %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :email, class: "col-sm-2 control-label", for: "inputEmail3" %>
                <div class="col-sm-10 input-group">
                  <span class="input-group-addon">
                    <span class="glyphicon glyphicon-envelope"></span>
                  </span>
                  <%= f.email_field :email, class: "form-control", id: "inputEmail3", placeholder:"Email" %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :password, class: "col-sm-2 control-label", for: "inputPassword3" %>
                <div class="col-sm-10 input-group">
                  <span class="input-group-addon">
                    <span class="glyphicon glyphicon-asterisk"></span>
                  </span>
                  <%= f.password_field :password, class: "form-control", id: "inputPassword3", placeholder:"Password" %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :'confirm password', class: "col-sm-2 control-label", for: "inputPassword3" %>
                <div class="col-sm-10 input-group">
                  <span class="input-group-addon">
                    <span class="glyphicon glyphicon-asterisk"></span>
                  </span>
                  <%= f.password_field :password_confirmation, class: "form-control", id: "inputPassword3", placeholder:"Password" %>
                </div>
              </div>

              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <%= f.submit :'Sign up', class: "btn btn-default" %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div> -->
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/pages/modals/temp_signs.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Register with Pin Pic</h4>
      </div>
      <div class="modal-body">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#signin" data-toggle="tab">Sign in</a></li>
          <li><a href="#signup" data-toggle="tab">Sign up</a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
          <div class="tab-pane fade in active" id="signin">
            <%= form_for(resource, :as => resource_name, :url => session_path(resource_name), html: { class: "form-horizontal top-30-margin" }) do |f| %>
              <div class="form-group">
                <%= f.label :email, class: "col-sm-2 control-label", for: "inputEmail3" %>
                <div class="col-sm-10 input-group">
                  <span class="input-group-addon">
                    <span class="glyphicon glyphicon-envelope"></span>
                  </span>
                  <%= f.email_field :email, :autofocus => true, class: "form-control", id: "inputEmail3", placeholder:"Email" %>
                </div>
              </div>
              <div class="form-group">
                <%= f.label :password, class: "col-sm-2 control-label", for: "inputPassword3" %>
                <div class="col-sm-10 input-group">
                  <span class="input-group-addon">
                    <span class="glyphicon glyphicon-asterisk"></span>
                  </span>
                  <%= f.password_field :password, class: "form-control", id: "inputPassword3", placeholder:"Password" %>
                </div>
              </div>
              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <div class="checkbox">
                    <% if devise_mapping.rememberable? -%>
                      <%= f.check_box :remember_me %> <%= f.label :remember_me %>
                    <% end -%>                  
                  </div>
                </div>
              </div>
              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <%= f.submit :'Sign in', class: "btn btn-default" %>
                </div>
              </div>
            <% end %> 
          </div>
          <div class="tab-pane fade" id="signup">
            <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), html: { class: "form-horizontal top-30-margin" }) do |f| %>
              <%= devise_error_messages! %>

              <div class="form-group">
                <%= f.label :email, class: "col-sm-2 control-label", for: "inputEmail3" %>
                <div class="col-sm-10 input-group">
                  <span class="input-group-addon">
                    <span class="glyphicon glyphicon-envelope"></span>
                  </span>
                  <%= f.email_field :email, :autofocus => true, class: "form-control", id: "inputEmail3", placeholder:"Email" %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :password, class: "col-sm-2 control-label", for: "inputPassword3" %>
                <div class="col-sm-10 input-group">
                  <span class="input-group-addon">
                    <span class="glyphicon glyphicon-asterisk"></span>
                  </span>
                  <%= f.password_field :password, class: "form-control", id: "inputPassword3", placeholder:"Password" %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :'confirm password', class: "col-sm-2 control-label", for: "inputPassword3" %>
                <div class="col-sm-10 input-group">
                  <span class="input-group-addon">
                    <span class="glyphicon glyphicon-asterisk"></span>
                  </span>
                  <%= f.password_field :password_confirmation, class: "form-control", id: "inputPassword3", placeholder:"Password" %>
                </div>
              </div>

              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <%= f.submit :'Sign up', class: "btn btn-default" %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div> -->
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/pins/_form.html.erb
<%= simple_form_for(@pin) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-danger" %>
  <%= f.full_error :image_content_type, class: "alert alert-danger" %>

  <div class="form-group">
      <%= f.input :image, label: "Upload an image" %>
      <%= f.input :description, as: :text, input_html: {rows: "3", class: "form-control"} %>
  </div>

    <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
    <div class="box">
      <%= link_to (image_tag pin.image(:medium)), pin %>
      <p class="description">
        <%= pin.description %>
      </p>
      <p>
        Posted by: 
        <strong>
          <%= pin.user.username  %>
        </strong>
      </p>
      <% if current_user == pin.user %> 
      <p>
        <%= link_to 'Edit', edit_pin_path(pin) %>
        <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
      </p>
      <% end %>  
    </div>    

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render "pages/home" %>

</div id="pins">
  <%= render @pins %>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="well">
        <%= image_tag @pin.image(:large) %>
        <p>
          <%= @pin.description %>
          <%= @pin.user.username %>
        </p>
        <% if current_user == @pin.user %>
          <%= link_to 'Edit', edit_pin_path(@pin) %> |
        <% end %>
        <%= link_to 'Back', pins_path %>    
      </div>
    </div>
  </div>